<div id="eddbk-service-page" v-cloak>
    <div class="vcloak--visible loading-container loading-container--white"></div>
    <service-bookings-application :session-lengths-count-limit="1"
                                  :availability-total-duration-limit="730"
                                  inline-template
    >
        <div class="vcloak--hidden">
            <?=$this->render('availability/service-availability-editor');?>
            <div>
                <label class="selectit">
                    <input value="1" type="checkbox" name="enable_booking" id="enable_booking" v-model="bookingsEnabled">
                    Enable booking for this download
                </label>
            </div>
            <div class="alert alert-warning mt-12" v-if="bookingsEnabled && isPossibleComplexSetup">
                <span class="dashicons dashicons-info"></span>
                <div class="pl-4 pr-4">
                    <div><strong>{{ _('Possible complex setup') }}</strong></div>
                    <div class="mt-4">
                        It could be slow to save this Service with the current bookings setup.
                        In some rare cases, the site may time out. To learn more, please
                        <a href="https://docs.eddbookings.com/article/402-complex-bookings-setups" target="_blank">click here</a>.
                    </div>
                </div>
            </div>
            <tabs :options="tabsConfig" v-model="activeTab" v-if="bookingsEnabled">
                <tab title="Session Length">
                    <?=$this->render('availability/tab-session-length');?>
                </tab>
                <tab title="Availability">
                    <?=$this->render('availability/tab-availability');?>
                </tab>
                <tab title="Display Options">
                    <?=$this->render('availability/tab-display-options');?>
                </tab>
            </tabs>
            <input type="hidden" name="eddbk[service_options]" :value="bookingOptionsFormData">
        </div>
    </service-bookings-application>
</div>

<?=$this->render('components');?>