<service-availability-editor inline-template>
    <div>
        <modal @close="closeModal"
               :active="modalState.isOn()"
        >
            <div slot="header">
                Service availability

                <div class="modal__close modal--right" @click="closeModal" v-if="!closeConfirming">&times;</div>
                <div class="modal__header-buttons modal--right" v-else>
                    <input type="button" class="button button-dark-solid" value="Close" @click="forceCloseModal">
                    <input type="button" class="button" value="Continue Editing" @click="continueEditing">
                </div>
            </div>

            <div slot="body" :class="isDoubleConfirming ? 'disabled' : ''">
                <div class="form-row">
                    <div class="form-row__label">Starting from</div>
                    <div class="form-row__input">
                        <datepicker name="fromDate" placeholder="-- / -- / ----" format="dd/MM/yyyy" v-model="model.fromDate" style="width: 90px"></datepicker>
<!--                        <input type="text" placeholder="-- / -- / ----" v-model="model.fromDate" style="width: 90px">-->
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-row__label">Available time</div>
                    <div class="form-row__input">
                        <vue-timepicker v-model="fromTimeModel" format="HH:mm" :class="model.isAllDay ? 'disabled':''" style="width: 90px"></vue-timepicker>
                        <span class="form-row__word">to</span>
                        <vue-timepicker v-model="toTimeModel" format="HH:mm" :class="model.isAllDay ? 'disabled':''" style="width: 90px"></vue-timepicker>

                        <label for="all-day" class="form-row__word">
                            <input type="checkbox" id="all-day" v-model="model.isAllDay"> All day
                        </label>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-row__label">Repeats</div>
                    <div class="form-row__input">
                        <select v-model="model.repeats" style="min-width: 90px">
                            <option value="never">Never</option>
                            <option value="daily">Daily</option>
                            <option value="weekly">Weekly</option>
                            <option value="monthly">Monthly</option>
                            <option value="yearly">Yearly</option>
                        </select>
                    </div>
                </div>

                <div class="form-row" v-if="model.repeats !== 'never'">
                    <div class="form-row__label">Repeats every</div>
                    <div class="form-row__input">
                        <select style="min-width: 90px" v-model="model.repeatsEvery">
                            <option :value="i" v-for="i in repeatingDuration">{{ i }}</option>
                        </select>
                        {{ repeatingTitle }}
                    </div>
                </div>

                <template v-if="model.repeats === 'weekly'">
                    <div class="form-row">
                        <div class="form-row__label">Repeats on</div>
                        <div class="form-row__input">
                            <selection-list :collection="repeatsOnCollection" v-model="model.repeatsOn" :multiple="true">
                                <label class="label__rared" :for="r.getKey(r.item)" slot-scope="r">
                                    <input type="checkbox"
                                           :id="r.getKey(r.item)"
                                           :value="r.getKey(r.item)"
                                           @change="r.select(r.item)"
                                           :checked="r.isItemSelected(r.item)"
                                    > {{ r.item.value }}
                                </label>
                            </selection-list>
                        </div>
                    </div>
                </template>

                <template v-if="model.repeats === 'monthly'">
                    <div class="form-row">
                        <div class="form-row__label">Repeats on</div>
                        <div class="form-row__input">
                            <selection-list :collection="repeatsOnCollection" v-model="model.repeatsOn" wrap="select">
                                <option :value="r.getKey(r.item)" slot-scope="r">{{ r.item.value }}</option>
                            </selection-list>
                        </div>
                    </div>
                </template>

                <div class="form-row" v-if="model.repeats !== 'never'">
                    <div class="form-row__label">Ends</div>
                    <div class="form-row__input">
                        <div>
                            <label for="ends-after" style="width: 90px; display: inline-block">
                                <input type="radio" id="ends-after" value="afterWeeks" v-model="model.repeatsEnds"> After
                            </label>
                            <input type="text" placeholder="4" style="width: 90px" v-model="model.repeatsEndsWeeks"> weeks
                        </div>

                        <div style="margin-top: 4px" class="inline-datepicker">
                            <label for="ends-on" style="width: 90px; display: inline-block">
                                <input type="radio" id="ends-on" value="onDate" v-model="model.repeatsEnds"> On
                            </label>
                            <datepicker name="repeatsEndsDate" v-model="model.repeatsEndsDate" placeholder="-- / -- / ----" format="dd/MM/yyyy" style="width: 90px"></datepicker>
                        </div>
                    </div>
                </div>

                <div class="form-row" v-if="model.repeats !== 'never'">
                    <div class="form-row__label">
                        Exclusions
                        <div class="form-row__description">
                            Days excluded from the availability range
                        </div>
                    </div>
                    <div class="form-row__input form-row__input--padded">
                        <div>
                            <a href="#set-new-exclusions" class="add-new" @click="exclusionsPickerVisible = !exclusionsPickerVisible">
                                {{ exclusionsPickerVisible ? '- Hide Exclusion\'s Picker' : '+ Set New Exclusions' }}
                            </a>
                        </div>

                        <div class="exclusions-datepicker" v-if="exclusionsPickerVisible">
                            <datepicker :inline="true" :highlighted="excludesDatesModels" @selected="excludeDateSelected" ref="exclusions"></datepicker>
                        </div>

                        <repeater :collection="excludesDatesCollection" class="exclusions-list" v-if="model.excludesDates.length">
                            <div class="exclusions-list__item" slot-scope="r">
                                <div class="exclusions-list__item-title" v-text="_getExclusionItemTitle(r.item)"></div>
                                <a href="#removed" class="trash-can trash-can--right" @click="r.remove(r.item)">
                                    <span class="trash-can__icon dashicons dashicons-trash"></span>
                                </a>
                            </div>
                        </repeater>
                    </div>
                </div>
            </div>

            <div slot="footer">
                <template v-if="!removeConfirming">
                    <div :class="isDoubleConfirming ? 'disabled' : ''">
                        <template v-if="model.id">
                            <input type="button" class="button button-alert" value="Delete" style="float: left" @click="removeConfirming = true">
                        </template>
                        <input type="button" class="button" value="Cancel" @click="closeModal">
                        <input type="button" class="button button-primary" value="Save" @click="saveItem">
                    </div>
                </template>
                <template v-else>
                    <div class="remove-confirm" style="float: left;">
                        Are you sure you want to delete this availability? There is no undo option.
                    </div>

                    <input type="button" class="button button-alert-solid" value="Yes, delete" @click="deleteItem">
                    <input type="button" class="button" value="Cancel" @click="removeConfirming = false">
                </template>
            </div>
        </modal>
    </div>
</service-availability-editor>