<div class="wide-form">
    <div class="wide-form__header">
        {{ _('Calendar and timezone options') }}
    </div>
    <div class="wide-form__row">
        <div class="wide-form__label" style="width: 100%;max-width: 600px">
            {{ _("Allow clients to change timezone in the booking wizard") }}
        </div>
        <div class="wide-form__input">
            <bool-switcher v-model="allowCustomerChangeTimezone"></bool-switcher>
        </div>
    </div>
</div>

<div class="wide-form">
    <div class="wide-form__header">
        {{ _('More options coming soon') }}
    </div>
</div>