<p class="info">
    Click on any time or day in the calendar bellow to start adding your available
    times for this service. You may set recurring availabilities to save time,
    exclude dates where the availability does not apply, and much more.
    <a href="#">Learn more.</a>
</p>
<div class="alert alert-warning" v-if="overlappingAvailabilities">
    <span class="dashicons dashicons-info"></span>
    <span>
        There are at least two availabilities for this service that overlap. Only one of these availabilities will be available to your clients in the booking wizard. We recommend removing one of them. <a href="#">Click here to learn more.</a>
    </span>
</div>
<div class="alert alert-warning" v-if="!availabilities.length">
    <span class="dashicons dashicons-info"></span>
    <span>
        There is no availability set for this service. Please add at least one available date and time in order to start accepting bookings for this service.
    </span>
</div>
<availability-calendar :availabilities="availabilities"
                       class="rc-calendar rc-calendar--availability"
                       @availability-click="openAvailabilityEditor"
                       :overlapping-availabilities.sync="overlappingAvailabilities"
/>
