<?php // Session length limit is one day, minus one second. So for hours max session length is 23 hours, less then day ?>
<session-length :session-length-limit="86399" inline-template>
    <div>
        <div class="alert alert-warning" style="margin-bottom: 0; margin-top: .5rem">
            <span class="dashicons dashicons-info"></span>
            <span>
                {{ _('The "day" and "week" durations for session lengths are coming soon.') }}
            </span>
        </div>
        <div class="session-length eddbk-inputs">
            <div class="flex-row">
                <fieldset class="session-length__options">
                    <legend>{{ _('Session Length') }}</legend>
                    <input type="number" step="1" min="1" placeholder="15" v-model="sessionDefault.sessionLength"
                           ref="sessionLength"
                           class="session-length__input"
                           :data-validation-error="_('Please enter a session length greater than 0.')"
                    >
                    <select v-model="sessionTimeUnit">
                        <option :value="unit.seconds" v-for="unit in timeUnits" :disabled="unit.disabled">{{ unit.title }}</option>
                    </select>
                </fieldset>
                <fieldset class="session-length__options">
                    <legend>{{ _('Price') }}</legend>
                    <div class="input-with-placeholder">
                        <span>$</span>
                        <input type="number" step="1" min="1" placeholder="20.00" v-model="sessionDefault.price"
                               class="session-length__input session-length__input--wide"
                               ref="price"
                               :data-validation-error="_('Please enter a session price. If this session duration is free, enter 0.')"
                        >
                    </div>
                </fieldset>
            </div>
            <div class="session-length__footer">
                <div class="session-length__buttons">
                    <input type="button"
                           class="button button-primary"
                           value="Add"
                           @click="addNewSession"
                    />
                </div>
                <transition name="fade-transition">
                    <div class="session-length__validation" v-if="validationError">
                        {{ validationError }}
                    </div>
                </transition>
            </div>
        </div>
        <hr/>
        <div class="session-bookable">
            <div class="session-bookable__title">
                {{ _('Bookable session lengths and prices.') }}
            </div>

            <div class="session-items" v-if="sessions.getItems().length">
                <div class="session-items__header">
                    <div class="session-head">
                        <div class="session-item__length">
                            {{ _('Session length') }}
                        </div>
                        <div class="session-item__price">
                            {{ _('Price') }}
                        </div>
                        <div class="session-item__action"></div>
                    </div>
                </div>
                <repeater :collection="sessions" class="session-items__holder">
                    <div class="session-item" slot-scope="r">
                        <div class="session-item__length">
                            {{ humanize(r.item.sessionLength) }}
                        </div>
                        <div class="session-item__price">
                            $ {{ r.item.price }}
                        </div>
                        <div class="session-item__action">
                            <span class="dashicons dashicons-trash" @click="r.remove(r.item)"></span>
                        </div>
                    </div>
                </repeater>
            </div>
            <p class="description" v-else>
                {{ _('Please add a session length and corresponding price above. You can add as many as you need, or just one.') }}
            </p>
        </div>
    </div>
</session-length>