<div class="wide-form">
    <div class="wide-form__header">
        Calendar and timezone options
    </div>
    <div class="wide-form__row">
        <div class="wide-form__label" style="width: 100%;max-width: 600px">
            Show dates and times on the site using the customer's timezone
        </div>
        <div class="wide-form__input">
            <bool-switcher v-model="useCustomerTimezone"></bool-switcher>
        </div>
    </div>
</div>

<div class="wide-form">
    <div class="wide-form__header">
        More options coming soon
    </div>
</div>