<bookings-list-view @edit="editBooking"
                    @delete="deleteBooking"
                    @update-filter="fetch"
                    @ready="clearBookings"
                    :is-loading="isLoading"
                    inline-template>
    <div :class="isLoading ? 'loading-container' : ''">
        <bookings-filter @submit="updateFilter" :search-string.sync="search" :status.sync="status"></bookings-filter>
        <list-table
            class="table-eddbk-bookings"
            :columns="columns"
            :rows="bookings"
            :actions="actions"
            :show-cb="false"
            :bulk-actions="[]"
            :total-pages="pagesCount"
            :total-items="bookingsCount"
            :per-page="10"
            :current-page="params.page"
            action-column="date"
            @pagination="goToPage"
            @action:click="onActionClick"
        >
            <template slot="filters">
                <select v-model="month">
                    <option selected :value="false">All months</option>
                    <option :value="number" v-for="number in 12">{{ _month(number) }}</option>
                </select>
                <select v-model="service">
                    <option :value="null">All Services</option>
                    <option :value="service.id" v-for="service in services">{{ service.name }}</option>
                </select>
                <button class="button" @click="updateFilter">Filter</button>
            </template>

            <template slot="date" slot-scope="data">
                <a href="#" @click.prevent="$emit('edit', data.row)">
                    <strong>{{ humanizeDate(data.row.start) }}</strong>
                </a>
                <span style="opacity: .6; margin-left: 4px">ID: {{ data.row.id }}</span>
                <span class="loading-inline" v-if="data.row.isDeleting"></span>
            </template>

            <template slot="client" slot-scope="data">
                <a href="#">
                    {{ data.row.client.name }}
                </a>
            </template>

            <template slot="service" slot-scope="data">
                <a href="#">
                    {{ data.row.service.name }}
                </a>
            </template>

            <template slot="status" slot-scope="data">
                <a href="#" @click.prevent="$emit('edit', data.row)" style="text-transform: capitalize">
                    {{ data.row.status }}
                </a>
            </template>
        </list-table>
    </div>
</bookings-list-view>